package com.tongtech.ti.cxf.demo.security.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.interceptor.InInterceptors;
import org.apache.cxf.interceptor.OutInterceptors;

/**
 * This class was generated by Apache CXF 2.7.6 2013-08-28T11:43:39.096+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://demo.ti.tongtech.com/security/", name = "ISecuriyDemo")
@XmlSeeAlso({ ObjectFactory.class })
// ====加入如下代码====
@InInterceptors(interceptors = { "org.apache.cxf.interceptor.LoggingInInterceptor" })
@OutInterceptors(interceptors = { "org.apache.cxf.interceptor.LoggingOutInterceptor" })
// ====加入代码结束====
public interface ISecuriyDemo {

	@WebResult(name = "out", targetNamespace = "")
	@RequestWrapper(localName = "input", targetNamespace = "http://demo.ti.tongtech.com/security/", className = "com.tongtech.ti.cxf.demo.security.service.Input")
	@WebMethod(action = "http://demo.ti.tongtech.com/security/input")
	@ResponseWrapper(localName = "inputResponse", targetNamespace = "http://demo.ti.tongtech.com/security/", className = "com.tongtech.ti.cxf.demo.security.service.InputResponse")
	public java.lang.String input(
			@WebParam(name = "in", targetNamespace = "") java.lang.String in);
}
