
package com.tongtech.ti.cxf.demo.security.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-28T11:43:39.100+08:00
 * Generated source version: 2.7.6
 * 
 */
 
public class ISecuriyDemo_ISecuriyServicePort_Server{

    protected ISecuriyDemo_ISecuriyServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ISecuriyDemoImpl();
        String address = "http://localhost:8080/sec";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ISecuriyDemo_ISecuriyServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
